#!/bin/sh
just stn_no_freeze_stn_optimizer stn_c10_no_freeze_stn_optimizer_rts_symm_thetacropspenalty_eps_200_pw_1 rotation_translation_scale_symmetric thetacropspenalty 200 1
just stn_no_freeze_stn_optimizer stn_c10_no_freeze_stn_optimizer_rts_symm_thetacropspenalty_eps_200_pw_2 rotation_translation_scale_symmetric thetacropspenalty 200 2
just stn_no_freeze_stn_optimizer stn_c10_no_freeze_stn_optimizer_rts_symm_thetacropspenalty_eps_100_pw_1 rotation_translation_scale_symmetric thetacropspenalty 100 1
just stn_no_freeze_stn_optimizer stn_c10_no_freeze_stn_optimizer_rts_symm_thetacropspenalty_eps_100_pw_2 rotation_translation_scale_symmetric thetacropspenalty 100 2
just stn_no_freeze_stn_optimizer stn_c10_no_freeze_stn_optimizer_rts_symm_thetacropspenalty_eps_50_pw_1 rotation_translation_scale_symmetric thetacropspenalty 50 1
just stn_no_freeze_stn_optimizer stn_c10_no_freeze_stn_optimizer_rts_symm_thetacropspenalty_eps_50_pw_2 rotation_translation_scale_symmetric thetacropspenalty 50 2
just stn_no_freeze_stn_optimizer stn_c10_no_freeze_stn_optimizer_rts_symm_thetacropspenalty_eps_10_pw_1 rotation_translation_scale_symmetric thetacropspenalty 10 1
just stn_no_freeze_stn_optimizer stn_c10_no_freeze_stn_optimizer_rts_symm_thetacropspenalty_eps_10_pw_2 rotation_translation_scale_symmetric thetacropspenalty 10 2
just stn_no_freeze_stn_optimizer stn_c10_no_freeze_stn_optimizer_rts_symm_thetaloss_eps_200_pw_1 rotation_translation_scale_symmetric thetaloss 200 1
just stn_no_freeze_stn_optimizer stn_c10_no_freeze_stn_optimizer_rts_symm_thetaloss_eps_200_pw_2 rotation_translation_scale_symmetric thetaloss 200 2
just stn_no_freeze_stn_optimizer stn_c10_no_freeze_stn_optimizer_rts_symm_thetaloss_eps_100_pw_1 rotation_translation_scale_symmetric thetaloss 100 1
just stn_no_freeze_stn_optimizer stn_c10_no_freeze_stn_optimizer_rts_symm_thetaloss_eps_100_pw_2 rotation_translation_scale_symmetric thetaloss 100 2
just stn_no_freeze_stn_optimizer stn_c10_no_freeze_stn_optimizer_rts_symm_thetaloss_eps_50_pw_1 rotation_translation_scale_symmetric thetaloss 50 1
just stn_no_freeze_stn_optimizer stn_c10_no_freeze_stn_optimizer_rts_symm_thetaloss_eps_50_pw_2 rotation_translation_scale_symmetric thetaloss 50 2
just stn_no_freeze_stn_optimizer stn_c10_no_freeze_stn_optimizer_rts_symm_thetaloss_eps_10_pw_1 rotation_translation_scale_symmetric thetaloss 10 1
just stn_no_freeze_stn_optimizer stn_c10_no_freeze_stn_optimizer_rts_symm_thetaloss_eps_10_pw_2 rotation_translation_scale_symmetric thetaloss 10 2
